linter:
  rules:
    avoid_print: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_breaks: true
    use_key_in_widget_constructors: true

    avoid_empty_else: true
    avoid_unused_constructor_parameters: true
    prefer_typing_uninitialized_variables: true
    always_specify_types: true
    prefer_is_empty: true
    prefer_is_not_empty: true


    # Optional readability
    sort_child_properties_last: true
    prefer_final_locals: true

metrics:
  cyclomatic-complexity: 10
  lines-of-code: 100
  number-of-arguments: 4
  max-nesting-level: 3


dcm:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    widgets-nesting-level: 5
    number-of-used-widgets: 20
